# Generated by Django 3.2.4 on 2021-07-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usr',
            new_name='user',
        ),
    ]
